[general]
import = [
  "themes/tokyonight_moon.toml",
]

[font]
size = 11

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"

[font.bold]
style = "Medium"

[font.offset]
x = 1
y = 0

[window]
decorations_theme_variant = "Dark"

[window.padding]
x = 5
y = 3

[window.dimensions]
columns = 160
lines = 40

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "On"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"
